#############################################################################
# Makefile for building: lab7.app/Contents/MacOS/lab7
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  lab8.pro
# Template: app
# Command: /Users/mirandamo/Qt/5.15.2/clang_64/bin/qmake -o Makefile lab8.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DGLM_FORCE_RADIANS -DQT_QML_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -std=c++14 -g -std=gnu++1y $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -I. -Isrc -Ics123_lib -Iglm -Iglew-1.10.0/include -I../../../../Qt/5.15.2/clang_64/lib/QtOpenGL.framework/Headers -I../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers -I../../../../Qt/5.15.2/clang_64/lib/QtGui.framework/Headers -I../../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/System/Library/Frameworks/AGL.framework/Headers/ -I. -I../../../../Qt/5.15.2/clang_64/mkspecs/macx-clang -F/Users/mirandamo/Qt/5.15.2/clang_64/lib
QMAKE         = /Users/mirandamo/Qt/5.15.2/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/mirandamo/Qt/5.15.2/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/mirandamo/Qt/5.15.2/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = lab71.0.0
DISTDIR = /Users/mirandamo/Documents/4th_Year/cs1230/CS123JAMB/.tmp/lab71.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -no-pie -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk -mmacosx-version-min=10.13 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/mirandamo/Qt/5.15.2/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/mirandamo/Qt/5.15.2/clang_64/lib -framework QtOpenGL -framework QtWidgets -framework QtGui -framework AppKit -framework Metal -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/mainwindow.cpp \
		src/main.cpp \
		src/glwidget.cpp \
		src/openglshape.cpp \
		cs123_lib/resourceloader.cpp \
		cs123_lib/errorchecker.cpp \
		src/gl/datatype/FBO.cpp \
		src/gl/datatype/VBO.cpp \
		src/gl/datatype/VBOAttribMarker.cpp \
		src/gl/datatype/VAO.cpp \
		src/gl/datatype/IBO.cpp \
		src/gl/textures/Texture.cpp \
		src/gl/textures/Texture2D.cpp \
		src/gl/textures/TextureParameters.cpp \
		src/gl/textures/TextureParametersBuilder.cpp \
		src/gl/textures/RenderBuffer.cpp \
		src/gl/textures/DepthBuffer.cpp \
		src/gl/GLDebug.cpp \
		src/databinding.cpp \
		src/settings.cpp \
		glew-1.10.0/src/glew.c \
		src/terrain.cpp qrc_shaders.cpp \
		moc_mainwindow.cpp \
		moc_glwidget.cpp \
		moc_databinding.cpp
OBJECTS       = mainwindow.o \
		main.o \
		glwidget.o \
		openglshape.o \
		resourceloader.o \
		errorchecker.o \
		FBO.o \
		VBO.o \
		VBOAttribMarker.o \
		VAO.o \
		IBO.o \
		Texture.o \
		Texture2D.o \
		TextureParameters.o \
		TextureParametersBuilder.o \
		RenderBuffer.o \
		DepthBuffer.o \
		GLDebug.o \
		databinding.o \
		settings.o \
		glew.o \
		terrain.o \
		qrc_shaders.o \
		moc_mainwindow.o \
		moc_glwidget.o \
		moc_databinding.o
DIST          = ../../../../Qt/5.15.2/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/qdevice.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/common/unix.conf \
		../../../../Qt/5.15.2/clang_64/mkspecs/common/mac.conf \
		../../../../Qt/5.15.2/clang_64/mkspecs/common/macx.conf \
		../../../../Qt/5.15.2/clang_64/mkspecs/common/sanitize.conf \
		../../../../Qt/5.15.2/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt/5.15.2/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt/5.15.2/clang_64/mkspecs/common/clang.conf \
		../../../../Qt/5.15.2/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Qt/5.15.2/clang_64/mkspecs/qconfig.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/toolchain.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/qml_debug.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/mac/mac.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/qt.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/resources_functions.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/resources.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/moc.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/uic.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/unix/thread.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/qmake_use.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/file_copies.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/lex.prf \
		lab8.pro src/mainwindow.h \
		src/glwidget.h \
		src/openglshape.h \
		cs123_lib/resourceloader.h \
		cs123_lib/errorchecker.h \
		src/gl/datatype/FBO.h \
		src/gl/datatype/VBO.h \
		src/gl/datatype/VBOAttribMarker.h \
		src/gl/datatype/VAO.h \
		src/gl/datatype/IBO.h \
		src/gl/shaders/ShaderAttribLocations.h \
		src/gl/textures/Texture.h \
		src/gl/textures/Texture2D.h \
		src/gl/textures/TextureParameters.h \
		src/gl/textures/TextureParametersBuilder.h \
		src/gl/textures/RenderBuffer.h \
		src/gl/textures/DepthBuffer.h \
		src/gl/GLDebug.h \
		cs123_lib/sphere.h \
		src/databinding.h \
		src/settings.h \
		glew-1.10.0/include/GL/glew.h \
		src/terrain.h src/mainwindow.cpp \
		src/main.cpp \
		src/glwidget.cpp \
		src/openglshape.cpp \
		cs123_lib/resourceloader.cpp \
		cs123_lib/errorchecker.cpp \
		src/gl/datatype/FBO.cpp \
		src/gl/datatype/VBO.cpp \
		src/gl/datatype/VBOAttribMarker.cpp \
		src/gl/datatype/VAO.cpp \
		src/gl/datatype/IBO.cpp \
		src/gl/textures/Texture.cpp \
		src/gl/textures/Texture2D.cpp \
		src/gl/textures/TextureParameters.cpp \
		src/gl/textures/TextureParametersBuilder.cpp \
		src/gl/textures/RenderBuffer.cpp \
		src/gl/textures/DepthBuffer.cpp \
		src/gl/GLDebug.cpp \
		src/databinding.cpp \
		src/settings.cpp \
		glew-1.10.0/src/glew.c \
		src/terrain.cpp
QMAKE_TARGET  = lab7
DESTDIR       = 
TARGET        = lab7.app/Contents/MacOS/lab7

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 11.0
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/mirandamo/Documents/4th_Year/cs1230/CS123JAMB/lab8.pro


include /Users/mirandamo/Qt/5.15.2/clang_64/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

lab7.app/Contents/MacOS/lab7: ui_mainwindow.h $(OBJECTS)  
	@test -d lab7.app/Contents/MacOS/ || mkdir -p lab7.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: lab8.pro ../../../../Qt/5.15.2/clang_64/mkspecs/macx-clang/qmake.conf ../../../../Qt/5.15.2/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/qdevice.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/common/unix.conf \
		../../../../Qt/5.15.2/clang_64/mkspecs/common/mac.conf \
		../../../../Qt/5.15.2/clang_64/mkspecs/common/macx.conf \
		../../../../Qt/5.15.2/clang_64/mkspecs/common/sanitize.conf \
		../../../../Qt/5.15.2/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt/5.15.2/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt/5.15.2/clang_64/mkspecs/common/clang.conf \
		../../../../Qt/5.15.2/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Qt/5.15.2/clang_64/mkspecs/qconfig.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/toolchain.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/qml_debug.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/mac/mac.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/qt.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/resources_functions.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/resources.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/moc.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/uic.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/unix/thread.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/qmake_use.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/file_copies.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt/5.15.2/clang_64/mkspecs/features/lex.prf \
		lab8.pro \
		shaders/shaders.qrc \
		../../../../Qt/5.15.2/clang_64/lib/QtOpenGL.framework/Resources/QtOpenGL.prl \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		../../../../Qt/5.15.2/clang_64/lib/QtGui.framework/Resources/QtGui.prl \
		../../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile lab8.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug
../../../../Qt/5.15.2/clang_64/mkspecs/features/spec_pre.prf:
../../../../Qt/5.15.2/clang_64/mkspecs/qdevice.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/features/device_config.prf:
../../../../Qt/5.15.2/clang_64/mkspecs/common/unix.conf:
../../../../Qt/5.15.2/clang_64/mkspecs/common/mac.conf:
../../../../Qt/5.15.2/clang_64/mkspecs/common/macx.conf:
../../../../Qt/5.15.2/clang_64/mkspecs/common/sanitize.conf:
../../../../Qt/5.15.2/clang_64/mkspecs/common/gcc-base.conf:
../../../../Qt/5.15.2/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../../Qt/5.15.2/clang_64/mkspecs/common/clang.conf:
../../../../Qt/5.15.2/clang_64/mkspecs/common/clang-mac.conf:
../../../../Qt/5.15.2/clang_64/mkspecs/qconfig.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_positioningquick.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_repparser.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_service_support_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../Qt/5.15.2/clang_64/mkspecs/features/qt_functions.prf:
../../../../Qt/5.15.2/clang_64/mkspecs/features/qt_config.prf:
../../../../Qt/5.15.2/clang_64/mkspecs/macx-clang/qmake.conf:
../../../../Qt/5.15.2/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../../Qt/5.15.2/clang_64/mkspecs/features/exclusive_builds.prf:
../../../../Qt/5.15.2/clang_64/mkspecs/features/mac/sdk.prf:
../../../../Qt/5.15.2/clang_64/mkspecs/features/toolchain.prf:
../../../../Qt/5.15.2/clang_64/mkspecs/features/mac/toolchain.prf:
../../../../Qt/5.15.2/clang_64/mkspecs/features/default_pre.prf:
../../../../Qt/5.15.2/clang_64/mkspecs/features/mac/default_pre.prf:
../../../../Qt/5.15.2/clang_64/mkspecs/features/resolve_config.prf:
../../../../Qt/5.15.2/clang_64/mkspecs/features/default_post.prf:
../../../../Qt/5.15.2/clang_64/mkspecs/features/mac/default_post.prf:
../../../../Qt/5.15.2/clang_64/mkspecs/features/mac/objective_c.prf:
../../../../Qt/5.15.2/clang_64/mkspecs/features/qml_debug.prf:
../../../../Qt/5.15.2/clang_64/mkspecs/features/mac/mac.prf:
../../../../Qt/5.15.2/clang_64/mkspecs/features/warn_on.prf:
../../../../Qt/5.15.2/clang_64/mkspecs/features/qt.prf:
../../../../Qt/5.15.2/clang_64/mkspecs/features/resources_functions.prf:
../../../../Qt/5.15.2/clang_64/mkspecs/features/resources.prf:
../../../../Qt/5.15.2/clang_64/mkspecs/features/moc.prf:
../../../../Qt/5.15.2/clang_64/mkspecs/features/unix/opengl.prf:
../../../../Qt/5.15.2/clang_64/mkspecs/features/uic.prf:
../../../../Qt/5.15.2/clang_64/mkspecs/features/unix/thread.prf:
../../../../Qt/5.15.2/clang_64/mkspecs/features/qmake_use.prf:
../../../../Qt/5.15.2/clang_64/mkspecs/features/file_copies.prf:
../../../../Qt/5.15.2/clang_64/mkspecs/features/mac/rez.prf:
../../../../Qt/5.15.2/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../../../Qt/5.15.2/clang_64/mkspecs/features/testcase_targets.prf:
../../../../Qt/5.15.2/clang_64/mkspecs/features/exceptions.prf:
../../../../Qt/5.15.2/clang_64/mkspecs/features/yacc.prf:
../../../../Qt/5.15.2/clang_64/mkspecs/features/lex.prf:
lab8.pro:
shaders/shaders.qrc:
../../../../Qt/5.15.2/clang_64/lib/QtOpenGL.framework/Resources/QtOpenGL.prl:
../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Resources/QtWidgets.prl:
../../../../Qt/5.15.2/clang_64/lib/QtGui.framework/Resources/QtGui.prl:
../../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile lab8.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE

lab7.app/Contents/PkgInfo: 
	@test -d lab7.app/Contents || mkdir -p lab7.app/Contents
	@$(DEL_FILE) lab7.app/Contents/PkgInfo
	@echo "APPL????" > lab7.app/Contents/PkgInfo
lab7.app/Contents/Resources/empty.lproj: 
	@test -d lab7.app/Contents/Resources || mkdir -p lab7.app/Contents/Resources
	@touch lab7.app/Contents/Resources/empty.lproj
	
lab7.app/Contents/Info.plist: 
	@test -d lab7.app/Contents || mkdir -p lab7.app/Contents
	@$(DEL_FILE) lab7.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.lab7,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.yourcompany.lab7,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.13,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,lab7,g" -e "s,@LIBRARY@,lab7,g" -e "s,\$${EXECUTABLE_NAME},lab7,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" ../../../../Qt/5.15.2/clang_64/mkspecs/macx-clang/Info.plist.app >lab7.app/Contents/Info.plist

all: Makefile \
		lab7.app/Contents/PkgInfo \
		lab7.app/Contents/Resources/empty.lproj \
		lab7.app/Contents/Info.plist lab7.app/Contents/MacOS/lab7

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents shaders/shaders.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../../../../Qt/5.15.2/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/mainwindow.h src/glwidget.h src/openglshape.h cs123_lib/resourceloader.h cs123_lib/errorchecker.h src/gl/datatype/FBO.h src/gl/datatype/VBO.h src/gl/datatype/VBOAttribMarker.h src/gl/datatype/VAO.h src/gl/datatype/IBO.h src/gl/shaders/ShaderAttribLocations.h src/gl/textures/Texture.h src/gl/textures/Texture2D.h src/gl/textures/TextureParameters.h src/gl/textures/TextureParametersBuilder.h src/gl/textures/RenderBuffer.h src/gl/textures/DepthBuffer.h src/gl/GLDebug.h cs123_lib/sphere.h src/databinding.h src/settings.h glew-1.10.0/include/GL/glew.h src/terrain.h $(DISTDIR)/
	$(COPY_FILE) --parents src/mainwindow.cpp src/main.cpp src/glwidget.cpp src/openglshape.cpp cs123_lib/resourceloader.cpp cs123_lib/errorchecker.cpp src/gl/datatype/FBO.cpp src/gl/datatype/VBO.cpp src/gl/datatype/VBOAttribMarker.cpp src/gl/datatype/VAO.cpp src/gl/datatype/IBO.cpp src/gl/textures/Texture.cpp src/gl/textures/Texture2D.cpp src/gl/textures/TextureParameters.cpp src/gl/textures/TextureParametersBuilder.cpp src/gl/textures/RenderBuffer.cpp src/gl/textures/DepthBuffer.cpp src/gl/GLDebug.cpp src/databinding.cpp src/settings.cpp glew-1.10.0/src/glew.c src/terrain.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r lab7.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -spec macx-clang CONFIG+=debug CONFIG+=qml_debug

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_shaders.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_shaders.cpp
qrc_shaders.cpp: shaders/shaders.qrc \
		../../../../Qt/5.15.2/clang_64/bin/rcc \
		shaders/verticalBlur.frag \
		shaders/phong.frag \
		shaders/particles_update.frag \
		shaders/shader.frag \
		shaders/particles_draw.vert \
		shaders/quad.vert \
		shaders/phong.vert \
		shaders/horizontalBlur.frag \
		shaders/texture.frag \
		shaders/shader.vert \
		shaders/particles_draw.frag
	/Users/mirandamo/Qt/5.15.2/clang_64/bin/rcc -name shaders shaders/shaders.qrc -o qrc_shaders.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../../../Qt/5.15.2/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -std=c++14 -g -std=gnu++1y $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk -mmacosx-version-min=10.13 -Wall -Wextra -dM -E -o moc_predefs.h ../../../../Qt/5.15.2/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_glwidget.cpp moc_databinding.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_glwidget.cpp moc_databinding.cpp
moc_mainwindow.cpp: src/mainwindow.h \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QList \
		../../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qlist.h \
		src/glwidget.h \
		glew-1.10.0/include/GL/glew.h \
		../../../../Qt/5.15.2/clang_64/lib/QtOpenGL.framework/Headers/QGLWidget \
		../../../../Qt/5.15.2/clang_64/lib/QtOpenGL.framework/Headers/qgl.h \
		../../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/fwd.hpp \
		glm/detail/type_int.hpp \
		glm/detail/setup.hpp \
		glm/detail/type_float.hpp \
		glm/detail/type_vec.hpp \
		glm/detail/precision.hpp \
		glm/detail/type_mat.hpp \
		glm/vec2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/vec3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/vec4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/mat2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/mat2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/mat2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/mat3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/mat3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/mat3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/mat4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/mat4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/mat4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/exponential.hpp \
		glm/detail/func_exponential.hpp \
		glm/detail/func_exponential.inl \
		glm/detail/func_vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/common.hpp \
		glm/detail/func_common.hpp \
		glm/detail/func_common.inl \
		glm/packing.hpp \
		glm/detail/func_packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/matrix.hpp \
		glm/detail/func_matrix.hpp \
		glm/detail/func_matrix.inl \
		glm/vector_relational.hpp \
		glm/integer.hpp \
		glm/detail/func_integer.hpp \
		glm/detail/func_integer.inl \
		glm/gtx/transform.hpp \
		glm/gtc/matrix_transform.hpp \
		glm/gtc/matrix_transform.inl \
		glm/gtx/transform.inl \
		glm/gtc/type_ptr.hpp \
		glm/gtc/quaternion.hpp \
		glm/gtc/constants.hpp \
		glm/gtc/constants.inl \
		glm/gtc/quaternion.inl \
		glm/gtc/type_ptr.inl \
		src/gl/datatype/FBO.h \
		src/gl/textures/TextureParameters.h \
		src/terrain.h \
		src/openglshape.h \
		src/gl/datatype/VBO.h \
		src/gl/datatype/VBOAttribMarker.h \
		moc_predefs.h \
		../../../../Qt/5.15.2/clang_64/bin/moc
	/Users/mirandamo/Qt/5.15.2/clang_64/bin/moc $(DEFINES) --include /Users/mirandamo/Documents/4th_Year/cs1230/CS123JAMB/moc_predefs.h -I/Users/mirandamo/Qt/5.15.2/clang_64/mkspecs/macx-clang -I/Users/mirandamo/Documents/4th_Year/cs1230/CS123JAMB -I/Users/mirandamo/Documents/4th_Year/cs1230/CS123JAMB/src -I/Users/mirandamo/Documents/4th_Year/cs1230/CS123JAMB/cs123_lib -I/Users/mirandamo/Documents/4th_Year/cs1230/CS123JAMB/glm -I/Users/mirandamo/Documents/4th_Year/cs1230/CS123JAMB/glew-1.10.0/include -I/Users/mirandamo/Qt/5.15.2/clang_64/lib/QtOpenGL.framework/Headers -I/Users/mirandamo/Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers -I/Users/mirandamo/Qt/5.15.2/clang_64/lib/QtGui.framework/Headers -I/Users/mirandamo/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/mirandamo/Qt/5.15.2/clang_64/lib src/mainwindow.h -o moc_mainwindow.cpp

moc_glwidget.cpp: src/glwidget.h \
		glew-1.10.0/include/GL/glew.h \
		../../../../Qt/5.15.2/clang_64/lib/QtOpenGL.framework/Headers/QGLWidget \
		../../../../Qt/5.15.2/clang_64/lib/QtOpenGL.framework/Headers/qgl.h \
		../../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/fwd.hpp \
		glm/detail/type_int.hpp \
		glm/detail/setup.hpp \
		glm/detail/type_float.hpp \
		glm/detail/type_vec.hpp \
		glm/detail/precision.hpp \
		glm/detail/type_mat.hpp \
		glm/vec2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/vec3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/vec4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/mat2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/mat2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/mat2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/mat3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/mat3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/mat3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/mat4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/mat4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/mat4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/exponential.hpp \
		glm/detail/func_exponential.hpp \
		glm/detail/func_exponential.inl \
		glm/detail/func_vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/common.hpp \
		glm/detail/func_common.hpp \
		glm/detail/func_common.inl \
		glm/packing.hpp \
		glm/detail/func_packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/matrix.hpp \
		glm/detail/func_matrix.hpp \
		glm/detail/func_matrix.inl \
		glm/vector_relational.hpp \
		glm/integer.hpp \
		glm/detail/func_integer.hpp \
		glm/detail/func_integer.inl \
		glm/gtx/transform.hpp \
		glm/gtc/matrix_transform.hpp \
		glm/gtc/matrix_transform.inl \
		glm/gtx/transform.inl \
		glm/gtc/type_ptr.hpp \
		glm/gtc/quaternion.hpp \
		glm/gtc/constants.hpp \
		glm/gtc/constants.inl \
		glm/gtc/quaternion.inl \
		glm/gtc/type_ptr.inl \
		src/gl/datatype/FBO.h \
		src/gl/textures/TextureParameters.h \
		src/terrain.h \
		src/openglshape.h \
		src/gl/datatype/VBO.h \
		src/gl/datatype/VBOAttribMarker.h \
		moc_predefs.h \
		../../../../Qt/5.15.2/clang_64/bin/moc
	/Users/mirandamo/Qt/5.15.2/clang_64/bin/moc $(DEFINES) --include /Users/mirandamo/Documents/4th_Year/cs1230/CS123JAMB/moc_predefs.h -I/Users/mirandamo/Qt/5.15.2/clang_64/mkspecs/macx-clang -I/Users/mirandamo/Documents/4th_Year/cs1230/CS123JAMB -I/Users/mirandamo/Documents/4th_Year/cs1230/CS123JAMB/src -I/Users/mirandamo/Documents/4th_Year/cs1230/CS123JAMB/cs123_lib -I/Users/mirandamo/Documents/4th_Year/cs1230/CS123JAMB/glm -I/Users/mirandamo/Documents/4th_Year/cs1230/CS123JAMB/glew-1.10.0/include -I/Users/mirandamo/Qt/5.15.2/clang_64/lib/QtOpenGL.framework/Headers -I/Users/mirandamo/Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers -I/Users/mirandamo/Qt/5.15.2/clang_64/lib/QtGui.framework/Headers -I/Users/mirandamo/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/mirandamo/Qt/5.15.2/clang_64/lib src/glwidget.h -o moc_glwidget.cpp

moc_databinding.cpp: src/databinding.h \
		../../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QVariant \
		../../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QSlider \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qslider.h \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QCheckBox \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qcheckbox.h \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QButtonGroup \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qbuttongroup.h \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QRadioButton \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qradiobutton.h \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QDockWidget \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qdockwidget.h \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QTabWidget \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qtabwidget.h \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QDial \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qdial.h \
		moc_predefs.h \
		../../../../Qt/5.15.2/clang_64/bin/moc
	/Users/mirandamo/Qt/5.15.2/clang_64/bin/moc $(DEFINES) --include /Users/mirandamo/Documents/4th_Year/cs1230/CS123JAMB/moc_predefs.h -I/Users/mirandamo/Qt/5.15.2/clang_64/mkspecs/macx-clang -I/Users/mirandamo/Documents/4th_Year/cs1230/CS123JAMB -I/Users/mirandamo/Documents/4th_Year/cs1230/CS123JAMB/src -I/Users/mirandamo/Documents/4th_Year/cs1230/CS123JAMB/cs123_lib -I/Users/mirandamo/Documents/4th_Year/cs1230/CS123JAMB/glm -I/Users/mirandamo/Documents/4th_Year/cs1230/CS123JAMB/glew-1.10.0/include -I/Users/mirandamo/Qt/5.15.2/clang_64/lib/QtOpenGL.framework/Headers -I/Users/mirandamo/Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers -I/Users/mirandamo/Qt/5.15.2/clang_64/lib/QtGui.framework/Headers -I/Users/mirandamo/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/mirandamo/Qt/5.15.2/clang_64/lib src/databinding.h -o moc_databinding.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: src/mainwindow.ui \
		../../../../Qt/5.15.2/clang_64/bin/uic
	/Users/mirandamo/Qt/5.15.2/clang_64/bin/uic src/mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

mainwindow.o: src/mainwindow.cpp src/mainwindow.h \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QList \
		../../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qlist.h \
		src/glwidget.h \
		glew-1.10.0/include/GL/glew.h \
		../../../../Qt/5.15.2/clang_64/lib/QtOpenGL.framework/Headers/QGLWidget \
		../../../../Qt/5.15.2/clang_64/lib/QtOpenGL.framework/Headers/qgl.h \
		../../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/fwd.hpp \
		glm/detail/type_int.hpp \
		glm/detail/setup.hpp \
		glm/detail/type_float.hpp \
		glm/detail/type_vec.hpp \
		glm/detail/precision.hpp \
		glm/detail/type_mat.hpp \
		glm/vec2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/vec3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/vec4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/mat2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/mat2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/mat2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/mat3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/mat3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/mat3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/mat4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/mat4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/mat4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/exponential.hpp \
		glm/detail/func_exponential.hpp \
		glm/detail/func_exponential.inl \
		glm/detail/func_vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/common.hpp \
		glm/detail/func_common.hpp \
		glm/detail/func_common.inl \
		glm/packing.hpp \
		glm/detail/func_packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/matrix.hpp \
		glm/detail/func_matrix.hpp \
		glm/detail/func_matrix.inl \
		glm/vector_relational.hpp \
		glm/integer.hpp \
		glm/detail/func_integer.hpp \
		glm/detail/func_integer.inl \
		glm/gtx/transform.hpp \
		glm/gtc/matrix_transform.hpp \
		glm/gtc/matrix_transform.inl \
		glm/gtx/transform.inl \
		glm/gtc/type_ptr.hpp \
		glm/gtc/quaternion.hpp \
		glm/gtc/constants.hpp \
		glm/gtc/constants.inl \
		glm/gtc/quaternion.inl \
		glm/gtc/type_ptr.inl \
		src/gl/datatype/FBO.h \
		src/gl/textures/TextureParameters.h \
		src/terrain.h \
		src/openglshape.h \
		src/gl/datatype/VBO.h \
		src/gl/datatype/VBOAttribMarker.h \
		ui_mainwindow.h \
		../../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QSettings \
		../../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qsettings.h \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QGridLayout \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qgridlayout.h \
		src/databinding.h \
		../../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QVariant \
		../../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QSlider \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qslider.h \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QCheckBox \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qcheckbox.h \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QButtonGroup \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qbuttongroup.h \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QRadioButton \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qradiobutton.h \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QDockWidget \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qdockwidget.h \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QTabWidget \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qtabwidget.h \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QDial \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qdial.h \
		src/settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o src/mainwindow.cpp

main.o: src/main.cpp ../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		src/mainwindow.h \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QList \
		../../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qlist.h \
		src/glwidget.h \
		glew-1.10.0/include/GL/glew.h \
		../../../../Qt/5.15.2/clang_64/lib/QtOpenGL.framework/Headers/QGLWidget \
		../../../../Qt/5.15.2/clang_64/lib/QtOpenGL.framework/Headers/qgl.h \
		../../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/fwd.hpp \
		glm/detail/type_int.hpp \
		glm/detail/setup.hpp \
		glm/detail/type_float.hpp \
		glm/detail/type_vec.hpp \
		glm/detail/precision.hpp \
		glm/detail/type_mat.hpp \
		glm/vec2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/vec3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/vec4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/mat2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/mat2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/mat2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/mat3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/mat3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/mat3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/mat4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/mat4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/mat4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/exponential.hpp \
		glm/detail/func_exponential.hpp \
		glm/detail/func_exponential.inl \
		glm/detail/func_vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/common.hpp \
		glm/detail/func_common.hpp \
		glm/detail/func_common.inl \
		glm/packing.hpp \
		glm/detail/func_packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/matrix.hpp \
		glm/detail/func_matrix.hpp \
		glm/detail/func_matrix.inl \
		glm/vector_relational.hpp \
		glm/integer.hpp \
		glm/detail/func_integer.hpp \
		glm/detail/func_integer.inl \
		glm/gtx/transform.hpp \
		glm/gtc/matrix_transform.hpp \
		glm/gtc/matrix_transform.inl \
		glm/gtx/transform.inl \
		glm/gtc/type_ptr.hpp \
		glm/gtc/quaternion.hpp \
		glm/gtc/constants.hpp \
		glm/gtc/constants.inl \
		glm/gtc/quaternion.inl \
		glm/gtc/type_ptr.inl \
		src/gl/datatype/FBO.h \
		src/gl/textures/TextureParameters.h \
		src/terrain.h \
		src/openglshape.h \
		src/gl/datatype/VBO.h \
		src/gl/datatype/VBOAttribMarker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

glwidget.o: src/glwidget.cpp src/glwidget.h \
		glew-1.10.0/include/GL/glew.h \
		../../../../Qt/5.15.2/clang_64/lib/QtOpenGL.framework/Headers/QGLWidget \
		../../../../Qt/5.15.2/clang_64/lib/QtOpenGL.framework/Headers/qgl.h \
		../../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/fwd.hpp \
		glm/detail/type_int.hpp \
		glm/detail/setup.hpp \
		glm/detail/type_float.hpp \
		glm/detail/type_vec.hpp \
		glm/detail/precision.hpp \
		glm/detail/type_mat.hpp \
		glm/vec2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/vec3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/vec4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/mat2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/mat2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/mat2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/mat3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/mat3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/mat3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/mat4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/mat4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/mat4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/exponential.hpp \
		glm/detail/func_exponential.hpp \
		glm/detail/func_exponential.inl \
		glm/detail/func_vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/common.hpp \
		glm/detail/func_common.hpp \
		glm/detail/func_common.inl \
		glm/packing.hpp \
		glm/detail/func_packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/matrix.hpp \
		glm/detail/func_matrix.hpp \
		glm/detail/func_matrix.inl \
		glm/vector_relational.hpp \
		glm/integer.hpp \
		glm/detail/func_integer.hpp \
		glm/detail/func_integer.inl \
		glm/gtx/transform.hpp \
		glm/gtc/matrix_transform.hpp \
		glm/gtc/matrix_transform.inl \
		glm/gtx/transform.inl \
		glm/gtc/type_ptr.hpp \
		glm/gtc/quaternion.hpp \
		glm/gtc/constants.hpp \
		glm/gtc/constants.inl \
		glm/gtc/quaternion.inl \
		glm/gtc/type_ptr.inl \
		src/gl/datatype/FBO.h \
		src/gl/textures/TextureParameters.h \
		src/terrain.h \
		src/openglshape.h \
		src/gl/datatype/VBO.h \
		src/gl/datatype/VBOAttribMarker.h \
		cs123_lib/resourceloader.h \
		cs123_lib/errorchecker.h \
		../../../../Qt/5.15.2/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../../../Qt/5.15.2/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../../Qt/5.15.2/clang_64/lib/QtGui.framework/Headers/QWheelEvent \
		src/settings.h \
		../../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qobject.h \
		src/gl/textures/Texture2D.h \
		src/gl/textures/Texture.h \
		src/gl/shaders/ShaderAttribLocations.h \
		cs123_lib/sphere.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o glwidget.o src/glwidget.cpp

openglshape.o: src/openglshape.cpp src/openglshape.h \
		glew-1.10.0/include/GL/glew.h \
		src/gl/datatype/VBO.h \
		src/gl/datatype/VBOAttribMarker.h \
		src/gl/datatype/VAO.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o openglshape.o src/openglshape.cpp

resourceloader.o: cs123_lib/resourceloader.cpp cs123_lib/resourceloader.h \
		glew-1.10.0/include/GL/glew.h \
		../../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QFile \
		../../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QTextStream \
		../../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qtextstream.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o resourceloader.o cs123_lib/resourceloader.cpp

errorchecker.o: cs123_lib/errorchecker.cpp cs123_lib/errorchecker.h \
		glew-1.10.0/include/GL/glew.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o errorchecker.o cs123_lib/errorchecker.cpp

FBO.o: src/gl/datatype/FBO.cpp src/gl/datatype/FBO.h \
		src/gl/textures/TextureParameters.h \
		glew-1.10.0/include/GL/glew.h \
		src/gl/GLDebug.h \
		src/gl/textures/RenderBuffer.h \
		src/gl/textures/DepthBuffer.h \
		src/gl/textures/Texture2D.h \
		src/gl/textures/Texture.h \
		src/gl/textures/TextureParametersBuilder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FBO.o src/gl/datatype/FBO.cpp

VBO.o: src/gl/datatype/VBO.cpp src/gl/datatype/VBO.h \
		glew-1.10.0/include/GL/glew.h \
		src/gl/datatype/VBOAttribMarker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o VBO.o src/gl/datatype/VBO.cpp

VBOAttribMarker.o: src/gl/datatype/VBOAttribMarker.cpp src/gl/datatype/VBOAttribMarker.h \
		glew-1.10.0/include/GL/glew.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o VBOAttribMarker.o src/gl/datatype/VBOAttribMarker.cpp

VAO.o: src/gl/datatype/VAO.cpp src/gl/datatype/VAO.h \
		glew-1.10.0/include/GL/glew.h \
		src/gl/datatype/VBO.h \
		src/gl/datatype/IBO.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o VAO.o src/gl/datatype/VAO.cpp

IBO.o: src/gl/datatype/IBO.cpp src/gl/datatype/IBO.h \
		glew-1.10.0/include/GL/glew.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o IBO.o src/gl/datatype/IBO.cpp

Texture.o: src/gl/textures/Texture.cpp src/gl/textures/Texture.h \
		glew-1.10.0/include/GL/glew.h \
		src/gl/GLDebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Texture.o src/gl/textures/Texture.cpp

Texture2D.o: src/gl/textures/Texture2D.cpp src/gl/textures/Texture2D.h \
		src/gl/textures/Texture.h \
		glew-1.10.0/include/GL/glew.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Texture2D.o src/gl/textures/Texture2D.cpp

TextureParameters.o: src/gl/textures/TextureParameters.cpp src/gl/textures/TextureParameters.h \
		glew-1.10.0/include/GL/glew.h \
		src/gl/GLDebug.h \
		src/gl/textures/Texture.h \
		src/gl/textures/Texture2D.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TextureParameters.o src/gl/textures/TextureParameters.cpp

TextureParametersBuilder.o: src/gl/textures/TextureParametersBuilder.cpp src/gl/textures/TextureParametersBuilder.h \
		src/gl/textures/TextureParameters.h \
		glew-1.10.0/include/GL/glew.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TextureParametersBuilder.o src/gl/textures/TextureParametersBuilder.cpp

RenderBuffer.o: src/gl/textures/RenderBuffer.cpp src/gl/textures/RenderBuffer.h \
		glew-1.10.0/include/GL/glew.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RenderBuffer.o src/gl/textures/RenderBuffer.cpp

DepthBuffer.o: src/gl/textures/DepthBuffer.cpp src/gl/textures/DepthBuffer.h \
		src/gl/textures/RenderBuffer.h \
		glew-1.10.0/include/GL/glew.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DepthBuffer.o src/gl/textures/DepthBuffer.cpp

GLDebug.o: src/gl/GLDebug.cpp src/gl/GLDebug.h \
		glew-1.10.0/include/GL/glew.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GLDebug.o src/gl/GLDebug.cpp

databinding.o: src/databinding.cpp src/databinding.h \
		../../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QVariant \
		../../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QSlider \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qslider.h \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QCheckBox \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qcheckbox.h \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QButtonGroup \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qbuttongroup.h \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QRadioButton \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qradiobutton.h \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QDockWidget \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qdockwidget.h \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QTabWidget \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qtabwidget.h \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QDial \
		../../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qdial.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o databinding.o src/databinding.cpp

settings.o: src/settings.cpp src/settings.h \
		../../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QFile \
		../../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QSettings \
		../../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settings.o src/settings.cpp

glew.o: glew-1.10.0/src/glew.c glew-1.10.0/include/GL/glew.h \
		glew-1.10.0/include/GL/wglew.h \
		glew-1.10.0/include/GL/glxew.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o glew.o glew-1.10.0/src/glew.c

terrain.o: src/terrain.cpp src/terrain.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/fwd.hpp \
		glm/detail/type_int.hpp \
		glm/detail/setup.hpp \
		glm/detail/type_float.hpp \
		glm/detail/type_vec.hpp \
		glm/detail/precision.hpp \
		glm/detail/type_mat.hpp \
		glm/vec2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/vec3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/vec4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/mat2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/mat2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/mat2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/mat3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/mat3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/mat3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/mat4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/mat4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/mat4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/exponential.hpp \
		glm/detail/func_exponential.hpp \
		glm/detail/func_exponential.inl \
		glm/detail/func_vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/common.hpp \
		glm/detail/func_common.hpp \
		glm/detail/func_common.inl \
		glm/packing.hpp \
		glm/detail/func_packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/matrix.hpp \
		glm/detail/func_matrix.hpp \
		glm/detail/func_matrix.inl \
		glm/vector_relational.hpp \
		glm/integer.hpp \
		glm/detail/func_integer.hpp \
		glm/detail/func_integer.inl \
		glm/gtx/transform.hpp \
		glm/gtc/matrix_transform.hpp \
		glm/gtc/matrix_transform.inl \
		glm/gtx/transform.inl \
		glm/gtc/type_ptr.hpp \
		glm/gtc/quaternion.hpp \
		glm/gtc/constants.hpp \
		glm/gtc/constants.inl \
		glm/gtc/quaternion.inl \
		glm/gtc/type_ptr.inl \
		src/openglshape.h \
		glew-1.10.0/include/GL/glew.h \
		src/gl/datatype/VBO.h \
		src/gl/datatype/VBOAttribMarker.h \
		src/gl/shaders/ShaderAttribLocations.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o terrain.o src/terrain.cpp

qrc_shaders.o: qrc_shaders.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_shaders.o qrc_shaders.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_glwidget.o: moc_glwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_glwidget.o moc_glwidget.cpp

moc_databinding.o: moc_databinding.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_databinding.o moc_databinding.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

